; PlatformIO Project Configuration File
;
; Default ESP32 receiver station project.

[env:dfrobot_firebeetle2_esp32s3]
platform = espressif32
board = dfrobot_firebeetle2_esp32s3
framework = arduino
monitor_speed = 115200
build_flags =
	-DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
	symlink://../telemetry_packet_lib
	jgromes/RadioLib@^7.6.0
	olikraus/U8g2@^2.36.12
